export const GET_SHOPPINGITEMS = 'GET_SHOPPINGITEMS';
export const SEARCH_SHOPPINGITEM = 'SEARCH_SHOPPINGITEM';
export const SET_SHOPPINGITEM = 'SET_SHOPPINGITEM';
export const ADD_SHOPPINGITEM = 'ADD_SHOPPINGITEM';
export const DEL_SHOPPINGITEM = 'DEL_SHOPPINGITEM';
export const ERR_SHOPPINGITEM = 'ERR_SHOPPINGITEM';
export const ITEM_CHECKED = 'ITEM_CHECKED';
export const SET_LOADING = 'SET_LOADING';